### ISSUE TITLE
Obtaining the flow length map in landlab

### ISSUE THREAD

**Issue by Giuseppecipolla95** [landlab/landlab#638] opened 2018-03-15 14:43 UTC
Hi to everyone! I'm working with watersheds and I'm wondering if there is a component in Landlab that allows to achieve the flow length grid. It has, in every node, the distance from that node to the watershed's outlet, according to the D8 method to set the paths. In Grass Gis it can be obtained with the command r.stream.distance. Thanks in advance!

**Comment by kbarnhart** [comment] 2018-03-15 14:56
@Giuseppecipolla95 this is not something that is presently implemented in landlab.

The closest thing that we have is the channel profiler which gets distances upstream along an extracted channel network. 

If you are not updating topography, you could save the output of r.stream.distance from Grass and add it to a model grid as a field. If you are using this in the context of changing topography, you could consider developing this functionality in landlab. Would this be something you'd be interested in?

I've marked this as an enhancement.

**Comment by Giuseppecipolla95** [comment] 2018-03-15 17:24
@kbarnhart I've been dealing with landlab for little time, so I'm a beginner, but I've an idea about how to set up this new component and maybe with your help I could achieve it. 
In my opinion, as first step, we should create a flow direction map where we are allowed to see the arrows that are representative of the flux direction from a node to another. If these arrows can be treated as links, the following step consists of setting their length (the diagonals are longer than verticals or horizontal links). In the third step, we should connect the consecutive links (or arrows) and determine the distance from each node to the watershed's outlet eventually as sum of consecutive links' length.
This is the code that allows me to find the drainage area map.
`from landlab.components import FlowRouter, DepressionFinderAndRouter
from landlab.io import read_esri_ascii
from landlab.plot import imshow_grid
from matplotlib.pyplot import figure, show
import watershed
import numpy as np 
from shapely.geometry import shape
import geopandas as gpd
import watershedinternal

(mg, z) = read_esri_ascii('oreto.txt', name='topographic__elevation')
mg.set_fixed_value_boundaries_at_grid_edges(True, True, True, True)

fr = FlowRouter(mg)
fr.route_flow()

mg.at_node['flow__receiver_node'].reshape(mg.shape)
mg.at_node['drainage_area'].reshape(mg.shape)
df = DepressionFinderAndRouter(mg)
df.map_depressions()
mg.at_node['flow__receiver_node'].reshape(mg.shape)
mg.at_node['drainage_area'].reshape(mg.shape)
figure()
imshow_grid(mg, mg['node']['drainage_area'])
show() `
And this is the drainage area map.
![image](https://user-images.githubusercontent.com/36881480/37479659-7522777a-287d-11e8-9d64-3ef76d7acc8b.png)

Do you know how to see the arrows?

**Comment by kbarnhart** [comment] 2018-03-15 18:46
@Giuseppecipolla95 

I'd recommend familiarizing yourself with the [FlowDirector](http://landlab.readthedocs.io/en/master/landlab.components.flow_director.html#module-landlab.components.flow_director) and [FlowAccumulator](http://landlab.readthedocs.io/en/master/landlab.components.flow_accum.html#module-landlab.components.flow_accum) components which are used to direct and accumulate flow. 

Make sure you have a developer version of landlab and when you look at the readthedocs page you use the master version of the docs (rather than the default version of latest). This can be changed the the lower-right corner.

These components create grid fields like `drainage_area` and the `flow__upstream_node_order` data structure which can be used to navigate the flow field in an order n manner. 

I'd also recommend reading more about the different attributes of the model grid (e.g. `length_of_link`) and how to [get information about the grid](http://landlab.readthedocs.io/en/master/landlab.grid.base.html#getting-information-about-a-grid).

I've taken a quick stab at making such a utility and will reference this issue in a quickly forthcoming Pull Request.

Here is a code snippet that highlights how this can be used. A few things to note: since we are developing a new tool within landlab, I don't want assume much about what beyond landlab and its dependencies a user may have. For this reason, I'm not using any extra modules (e.g. geopandas) and I'm not importing a file. Here is some additional information about [minimally complete and verifiable code](https://stackoverflow.com/help/mcve) example.


```python
# import required modules
from landlab import RasterModelGrid
from landlab.components import FlowAccumulator, FastscapeEroder
import numpy as np
from landlab.plot import imshow_grid
from landlab.utils.stream_length import calculate_stream_length

# make a simple LEM to evolve some topography
mg = RasterModelGrid(30, 70)
z = mg.add_zeros('topographic__elevation', at='node')
z += 200 + mg.x_of_node + mg.y_of_node + np.random.randn(mg.size('node'))

mg.set_closed_boundaries_at_grid_edges(bottom_is_closed=True, left_is_closed=True, right_is_closed=True, top_is_closed=True)
mg.set_watershed_boundary_condition_outlet_id(0, z, -9999)
fa = FlowAccumulator(mg, flow_director='D8')
sp = FastscapeEroder(mg, K_sp=.0001, m_sp=.5, n_sp=1)

dt = 100
for i in range(200):
    fa.run_one_step()
    sp.run_one_step(dt=dt)
    mg.at_node['topographic__elevation'][0] -= 0.001 # Uplift
    

# plot the topography
imshow_grid(mg, 'topographic__elevation')

# calculate stream length
stream__length = calculate_stream_length(mg, add_to_grid=True, noclobber=False)

# plot stream length
imshow_grid(mg, 'stream__length')

```

Take a look at the Pull Request and this snippet. 

If you'd like to take development from here and develop a set of tests that will verify that this utility is working as expected and works with `RasterModelGrids`, irregular grids like `HexModelGrid`, that would be fantastic. 

We create tests as standalone scripts in test folder as well as as part of docstrings. Some information about creating tests as docstrings[ is located in this tutorial.
](https://nbviewer.jupyter.org/github/landlab/tutorials/blob/master/making_components/making_components.ipynb#Doc-tests). I've created two example tests in the test folder to give you a sense of how these tests work.

I'd be happy to help you through this process.

**Comment by Giuseppecipolla95** [comment] 2018-03-17 10:13
@kbarnhart Thanks for your suggestions. I've tried to run your code snippet by using the stream_length utility but, at a certain point, the code stopped working due to this attribute error:
AttributeError: 'RasterModelGrid' object has no attribute 'length_of_d8'
I've also run the code after I had commented this code line and I've come across this index error:
IndexError: index 4100 is out of bounds for axis 0 with size 4100

Have you encountered these issues? 
If this utility works as expected, I'll share the whole code with the output (flow length map) and I'll run it for other parts of Sicily. Do you think it will be a good example to adfirm that the utility works for some real landscapes?

**Comment by kbarnhart** [comment] 2018-03-17 22:22
@Giuseppecipolla95 

I've just re-run the snippet I'm not able to reproduce your error. There were some issues with the `FastscapeEroder` on `HexModelGrids` and `length_of_d8` but these were fixed with PR #637 and now that these improvements are in `master` I've merged them into this branch. 

Maybe make sure that your landlab is up to date and you are on the correct branch. 


When I run this code I get the following two images. First the image of the topography:

![topo](https://user-images.githubusercontent.com/6589339/37560494-cbea8afc-29fe-11e8-85d7-d0f3279b792c.png)

And this image for stream length:
![stream_length](https://user-images.githubusercontent.com/6589339/37560497-db1de816-29fe-11e8-8098-a64fff5d26cf.png)

Regarding next steps. The intention of the tests is not to have a full landscape scale example, but to make a small example in which we can know for sure exactly what the answer should be. We then write a code for which we know exactly what the output should be and then every time the code is tested we can check that the output the code produces is what it should be. 

An example for this application might be to make by hand a 6 x 6 grid of topography, and also a grid of stream length. We would do this for both D8 and D4 flow routing methods. 

With this we can test that the stream utility is calculating stream length correctly. 

Does this make sense?

**Comment by Giuseppecipolla95** [comment] 2018-03-19 07:54
@kbarnhart I was able to reproduce your output maps by updating my version of Python and Landlab.
Regarding next steps, I've understood what you want to mean. I'll provide you a few tests of stream length utility.

**Comment by kbarnhart** [comment] 2018-03-20 13:39
@Giuseppecipolla95 thanks for the update. Glad you were able to get it to work. Let me know if you have any questions or want to discuss anything as you continue to work on this.

**Comment by Giuseppecipolla95** [comment] 2018-03-21 13:43
@kbarnhart I've developped two examples of the stream_length utility, one with a regular grid and the other with an irregular grid. In these applications the flow direction can be calculated with both D8 and D4 methods by using the FlowRouter component.
Here is the test for regular grid:

`#Test 1: Regular grid D8 and D4 algorithm with Flow Router
from landlab.components import FlowRouter
from landlab import RasterModelGrid
import numpy as np
from landlab.utils.stream_length import calculate_stream_length
from landlab.plot import imshow_grid
from matplotlib.pyplot import figure

mg = RasterModelGrid((5, 4), spacing=(1, 1))
z = np.array ([[0,0,0,0],[0,21,10,0],[0,31,20,0],[0,32,30,0],[0,0,0,0]],dtype='float64')
_ = mg.add_field('node','topographic__elevation', z)
figure(); imshow_grid(mg,mg['node']['topographic__elevation'])

mg.set_closed_boundaries_at_grid_edges(bottom_is_closed=True, left_is_closed=True, right_is_closed=True, top_is_closed=True)

fr = FlowRouter(mg, method = 'D4') #Set D4 or D8 method
fr.route_flow()

stream__length = calculate_stream_length(mg, add_to_grid=True, noclobber=False)

#Boundary nodes and the outlet shauldn't have stream_length value different from 0
flow_length = stream__length-stream__length[6]
mg.add_field('node','flow_length',flow_length)
figure(); imshow_grid(mg,mg['node']['flow_length'])`

I've realized that the stream_length provides a value of length different from zero at boundary nodes, which height has been set to zero, and above all at the outlet node, that definitely has to be equal to zero. For this reason, I think that the outlet value of the stream length utility should be subtracted to all pixels. As you can see, if you run this code you'll achieve the expected flow length map that highlights that the utility works as expected. 

Here is the code of the test for an irregular grid:
`from landlab import HexModelGrid, CLOSED_BOUNDARY
from landlab.components import FlowRouter
import numpy as np
from landlab.utils.stream_length import calculate_stream_length
from landlab.plot import imshow_grid
from matplotlib.pyplot import figure

dx=(2./(3.**0.5))**0.5
hmg = HexModelGrid(5,3, dx)
_ = hmg.add_field('topographic__elevation', hmg.node_x + np.round(hmg.node_y), at = 'node')
figure(); imshow_grid(hmg,hmg['node']['topographic__elevation'])
hmg.status_at_node[0] = CLOSED_BOUNDARY

fr = FlowRouter(hmg, method = 'D4') #Set D4 or D8 method
fr.route_flow()

stream__length = calculate_stream_length(hmg, add_to_grid=True, noclobber=False)

#Boundary nodes and the outlet shauldn't have stream_length value different from 0
flow_length = stream__length-stream__length[4]
hmg.add_field('node','flow_length',flow_length)
figure(); imshow_grid(hmg,hmg['node']['flow_length'])`

Futhermore I've applied the program to my watershed. I know you said that it shouldn't be an example but, as far as I'm concerned, this could be useful for anyone who will run into my same problem. 
This is the code:

`from landlab.components import FlowRouter, DepressionFinderAndRouter
from landlab.io import read_esri_ascii
from landlab.plot import imshow_grid
from matplotlib.pyplot import figure, show
import watershed
import numpy as np
from landlab.utils.stream_length import calculate_stream_length

(mg, z) = read_esri_ascii('nocella.txt', name='topographic__elevation')
mg.set_fixed_value_boundaries_at_grid_edges(True, True, True, True)

fr = FlowRouter(mg)
fr.route_flow()
mg.at_node['flow__receiver_node'].reshape(mg.shape)
mg.at_node['drainage_area'].reshape(mg.shape)

df = DepressionFinderAndRouter(mg)
df.map_depressions()
mg.at_node['flow__receiver_node'].reshape(mg.shape)
mg.at_node['drainage_area'].reshape(mg.shape)
imshow_grid(mg, mg['node']['drainage_area'])
show() 
mg.save('fiume.asc')

figure()
ws_mask = watershed.get_watershed_mask(mg, 95913)
imshow_grid(mg, ws_mask)

z_watershed=np.zeros(len(ws_mask))
for i in range (0,len(ws_mask)):
    if ws_mask[i]==True:
        z_watershed[i]=z[i]
    else:
        z_watershed[i]=0
mg.add_field('node','z_watershed',z_watershed)
figure(); imshow_grid(mg, mg['node']['z_watershed'])

stream__length = calculate_stream_length(mg, add_to_grid=True, noclobber=False)

flow_length = np.zeros(len(ws_mask))
for i in range (0,len(ws_mask)):
    if ws_mask[i]==True:
        flow_length[i]=stream__length[i]-stream__length[95913]
    else:
        flow_length[i]=0

mg.add_field('node','flow_length',flow_length)
figure(); imshow_grid(mg, mg['node']['flow_length'])`

The first part of the code allows to obtain the watershed. Then, I've masked the whole flow length map at my watershed and I've done the same subtraction operation as before. This is the output flow length map:
![image](https://user-images.githubusercontent.com/36881480/37712662-d695c264-2d14-11e8-86f9-902413e6b1d2.png)
And this is the map I've obtained from GRASS GIS.
![image](https://user-images.githubusercontent.com/36881480/37712851-63d00db0-2d15-11e8-9dcd-33a8d21f7488.png)

The comparison between the two maps displays that the utility works in the best way. Let me know your opinion!

**Comment by kbarnhart** [comment] 2018-03-21 21:04
@Giuseppecipolla95, this looks nice. 

I think it would make sense for you to develop your watershed example into a tutorial. 

Regarding the tests, I think you are off to a good start. I'd recommend that check out the branch I've started, create a branch off of it, and then add the code you've created to the tests. 

Rather than plotting the output as a test, you'll need to create a numpy array that represents the answer you know you should get and then use a function like `assert_array_equal` to verify that your result is correct. You'll see that I've already imported many of the most useful functions like `assert_array_equal` in the file `landlab/utils/tests/test_stream_length.py`. 

To checkout my branch, and then make a new branch off of it,  you should be able to type:

```
git fetch origin
git checkout -b barnhark/make_stream_length_utility origin/barnhark/make_stream_length_utility
git checkout -b Giuseppecipolla95/make_stream_length_utility
```

Also, if you type  

\```python


 before you code blocks and 

\```

after your code blocks, they will get formatted like python. [See this link ](https://guides.github.com/features/mastering-markdown/)for more information about markdown formatting.  

I've also made two small changes to the code that address your point that boundary nodes and the outlet shauldn't have stream_length value different from 0. 

If you find additional errors or want to make additional improvements, you should make them directly on your branch and then submit a pull request.

**Comment by Giuseppecipolla95** [comment] 2018-03-24 14:48
@kbarnhart I didn't have luck with the way you suggested to check out your branch and make a new branch off of it. When I typed git fetch origin into git-bash I encountered this error:

fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

However, I was able to create my branch and submit a pull request following the passages indicated on this website (https://guides.github.com/activities/hello-world/). In this pull request I've added my tests of stream length utility.

**Comment by Giuseppecipolla95** [comment] 2018-03-25 17:34
@kbarnhart Following your instructions I've created my new branch off of yours, as it can be seen from this screenshot.
![image](https://user-images.githubusercontent.com/36881480/37877967-782b3230-3062-11e8-805e-887cc0aacdc2.png)
After this, should I create a new pull request in the main branch of Landlab, the page showed in the following screenshot?
![image](https://user-images.githubusercontent.com/36881480/37878016-ff7cb9d4-3062-11e8-9008-cc81bac9834b.png)
If yes, should I create a new file about the test_of_stream_length as you did in your pull request, like shown by the following image?
![image](https://user-images.githubusercontent.com/36881480/37878033-52db469a-3063-11e8-8303-35c54f5a22ea.png)

**Comment by kbarnhart** [comment] 2018-03-25 18:03
@Giuseppecipolla95 

If you have made your branch off of my branch, you should already have a file called `landlab/landlab/utils/tests/test_stream_length.py` in your branch. You shouldn't need to create a new file.  

You should edit this file to add the tests and commit those changes to your branch. You'll want to verify that the tests you've added pass on your computer. You can do this[ the same way you check that the tests pass after a developer install](https://github.com/landlab/landlab/wiki/Installing-Landlab-from-source-code-(%22developer-install%22)#testing-your-install). 

Once you are happy that the utility is functioning as you expect it to, that it is fully tested, and that the tests pass, you should submit a pull request in which you request that your stream length utility development branch is merged the landlab master branch.

**Comment by Giuseppecipolla95** [comment] 2018-03-30 09:27
@kbarnhart pull request created. Let me know if everything is ok.

**Closed** 2018-05-30 15:09 UTC
Labels: enhancement
