### ISSUE TITLE
D4 flow direction raster

### ISSUE THREAD

**Issue by rbunel** [landlab/landlab#784] opened 2018-09-06 14:47 UTC
Hello,

I'm trying to create from my dem - filled with the D4 method - a D4 flow direction raster with 4 codes in my legend, one code for each flow direction.

Is this possible with landlab?
Thank you in advance for your answer.

**Comment by kbarnhart** [comment] 2018-09-06 14:59
@rbunel thanks for the question. That is not presently exposed in landlab but it is possible. 

If you wanted to do that you would need to look at the `flow__receiver_node` at-node grid field and the `grid.neighbors_at_node` attribute. The first of these lists the node ID where flow is directed. The second lists all four D4 neighbors of each node (in East, North, West, South order). By comparing these two fields at each node, you should be able to create a flow direction raster.

**Comment by rbunel** [comment] 2018-09-06 16:53
Thank you for your help.
Do you think there are other tools than Landlab to calculate the D4 flow direction ?

**Comment by kbarnhart** [comment] 2018-09-06 17:34
@rbunel I am not super well versed in other tools. It would be quite easy to do in Landlab, though. 

For example, consider this code snippet. 

```python
# import necessary modules
import numpy as np
np.random.seed(42)
from landlab import RasterModelGrid, imshow_grid
from landlab.components import (FlowAccumulator,
                                FastscapeEroder)


# create a model grid and add some random noise
mg = RasterModelGrid(30, 30, 100)
z = mg.add_zeros('topographic__elevation', at='node')
z += np.random.rand(z.size)


# instantiate components and evolve some topography. Use D4 flow routing. 
fa = FlowAccumulator(mg, flow_director='D4')
sp = FastscapeEroder(mg, K_sp=.0001, m_sp=.5, n_sp=1)

dt = 1000
for i in range(1000):
    fa.run_one_step()
    sp.run_one_step(dt=dt)
    mg.at_node['topographic__elevation'][mg.core_nodes] += 0.001 * dt

# make a plot of the topography
imshow_grid(mg, z, cmap='terrain', output='exampletopo.png')

# instatiate an at-node grid field for the d4 flow directions
d4_fd = mg.add_zeros('d4_flow_directions', at='node')

# make a variable for convenience for the flow reciever node field
r = mg.at_node['flow__receiver_node']


# compare r with each column of neighbors at node. Its in ENWS order. 
# Depending on what one needs, can replace the values I've used here with
# desired values for the output array. 

# Note that here a value of 0 would indicate that there is a sink or a boundary. 

# East
d4_fd[r == mg.neighbors_at_node[:,0]] = 90.0

# North
d4_fd[r == mg.neighbors_at_node[:,1]] = 360.0

# West
d4_fd[r == mg.neighbors_at_node[:,2]] = 270.0

# South
d4_fd[r == mg.neighbors_at_node[:,3]] = 180.0


# make a plot
imshow_grid(mg, d4_fd, cmap='viridis', output='example_flow_dirs.png')
```

Here is what the topography looks like
![exampletopo](https://user-images.githubusercontent.com/6589339/45174680-b69b3280-b1c8-11e8-8345-f8273e00b507.png)

And here is what the D4 flow directions look like:
![example_flow_dirs](https://user-images.githubusercontent.com/6589339/45174703-c31f8b00-b1c8-11e8-980a-f5fd8a0e391d.png)

**Comment by rbunel** [comment] 2018-09-07 09:19
@kbarnhart  Thank you for this very detailed answer with an example to support it.

I have a first problem, the command: from landlab.components import FlowAccumulator.
I get the following error.
`Traceback (most recent call last):`
  `Python Shell, prompt 56, line 1`
`ImportError: cannot import name FlowAccumulator`

I tried to replace this module with FlowRouter that I imported with this command : 
`from landlab.components.flow_routing import FlowRouter`

Here is the dem and the complete script.
[beau_filled2.txt](https://github.com/landlab/landlab/files/2360342/beau_filled2.txt)


`from landlab.io import read_esri_ascii`
`#from landlab.components import FlowAccumulator`
`from landlab.components.flow_routing import FlowRouter`

`watershed_dem ="C:/Path/To/beau_filled2.txt"`
`mg, z = read_esri_ascii(watershed_dem, name='topographic__elevation')`

`fr = FlowRouter(mg, method = 'D4')`
`fr.run_one_step()`

`d4_fd = mg.add_zeros('d4_flow_directions', at='node')`
`r = mg.at_node['flow__receiver_node']`

`#East`
`mg.at_node['d4_flow_directions'][r == mg.neighbors_at_node[:,0]] = 1`

`#North`
`d4_fd[r == mg.neighbors_at_node[:,1]] = 64`

`#West`
`d4_fd[r == mg.neighbors_at_node[:,2]] = 16`

`#South`
`d4_fd[r == mg.neighbors_at_node[:,3]] = 4`

`from landlab.io.esri_ascii import write_esri_ascii`
`write_esri_ascii('C:/Path/To/d4_fd.asc',mg)`

Everything seems to work very well except when the algorithm encounters flat areas for which the flow direction is not defined. You can see it on this image black pixels inside the basin representing pixels with no defined flow direction .The dem (beau_filled2.txt) is however without sinks since this dem is the output of the function SinkFiller with  routing='D4 and apply_slope=False. I didn't apply a slope to solve the flat areas because when I try, the function produces errors. This is the subject of this post #781 I opened.

However, I would like to define directions for these flat areas as ArcGIS can do with its D8 function.
Would the use of FlowAccumulator (which I can't import) instead of FlowRouter could fix this problem?




![d4_flow_direction](https://user-images.githubusercontent.com/42864541/45208381-bb281f80-b28a-11e8-9632-88be94585a26.png)

**Comment by rbunel** [comment] 2018-09-07 13:31
@kbarnhart. Thank you for your great reactivity and your time.

I use the release version that I installed with conda. Although I don't use a developer install, I still uninstalled and reinstalled landlab with these commands in the terminal shell.

`conda uninstall landlab`

```ruby
Solving environment: done
## Package Plan ##
  environment location: C:\Users\bunelrap\AppData\Local\Continuum\anaconda2
  removed specs:
    - landlab
The following packages will be REMOVED:
    landlab: 1.0.0beta.12-py27_0 landlab
Proceed ([y]/n)? y
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

`conda install landlab -c landlab -c conda-forge`

```
Solving environment: done
## Package Plan ##
  environment location: C:\Users\bunelrap\AppData\Local\Continuum\anaconda2
  added / updated specs:
    - landlab
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.11               |           py27_0         660 KB  conda-forge
    certifi-2018.4.16          |           py27_0         143 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         802 KB

The following NEW packages will be INSTALLED:
    landlab: 1.0.0beta.12-py27_0 landlab
The following packages will be UPDATED:
    certifi: 2018.4.16-py27_0            --> 2018.4.16-py27_0 conda-forge
    conda:   4.5.11-py27_0               --> 4.5.11-py27_0    conda-forge
Proceed ([y]/n)? y
Downloading and Extracting Packages
conda-4.5.11         | 660 KB    | ############################################################################ | 100%
certifi-2018.4.16    | 143 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Obviously, the uninstallation and reinstallation were done correctly.

In spyder : 
```ruby
import landlab

landlab.__version__
"1.0.0.0-beta.12

from landlab.components import FlowAccumulator

Traceback (most recent call last):

  File "<ipython-input-4-eb1412f9fe93>", line 1, in <module>
    from landlab.components import FlowAccumulator

ImportError: cannot import name FlowAccumulator
```
I can't get the most recent version. And this is the version that appears in the terminal shell during installation.

**Comment by mcflugen** [comment] 2018-09-07 13:36
@rbunel This is a *really* old version of landlab. Please try the following,
```
$ conda update landlab -c conda-forge
```
This should install version 1.5.2.

**Comment by SiccarPoint** [comment] 2018-09-07 13:43
This also seems like it could be a Python versioning issue to me, but let's try and solve this Eric's easy way first...

**Comment by kbarnhart** [comment] 2018-09-07 13:44
Assuming this works, lets make sure we (me, @mcflugen , @SiccarPoint , others) make sure the provided commands in the docs are all work as we expect. Since the 

```
conda install landlab -c landlab -c conda-forge
```
 command is exactly what we have on our QuickStart page. Thought when I run this command I am prompted to download version 1.5.2 (I'm running OSX/python 2.7)

@mcflugen, if I recall correctly, we recently had some issues related to conda thinking that the versions tagged with 'vXXX' were older than those that weren't. Do you think this may have happened for a similar reason?

**Comment by rbunel** [comment] 2018-09-07 13:53
Thanks to all of you. 
`conda update landlab -c conda-forge` in the terminal shell allowed me to get version 1.5.2.
So in my case, this command is necessary after I realized `conda install landlab -c landlab -c conda-forge` 

I'm trying to apply SinkFiller with this new version. I'll tell you if it works.

**Comment by rbunel** [comment] 2018-09-07 14:09
`rmg.set_watershed_boundary_condition_condition_condition_condition(z,nodata_value=-999999.)` gives me this error:
```python
Traceback (most recent call last):

  File "<ipython-input-9-0c357ab5354b>", line 12, in <module>
    rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\grid\raster.py", line 3934, in set_watershed_boundary_condition
    '\nUse the method set_watershed_boundary_condition_outlet_id '

ValueError: Grid has two potential outlet nodes.They have the following node IDs: 
[107 319 320 321 322]
Use the method set_watershed_boundary_condition_outlet_id to explicitly select one of these IDs as the outlet node.
```
How does `set_watershed_boundary_condition_outlet_id ` command work?

**Comment by kbarnhart** [comment] 2018-09-07 14:13
@rbunel have you found the [Index](https://landlab.readthedocs.io/en/latest/genindex.html) in the [Reference Manual](https://landlab.readthedocs.io/en/latest/#developer-documentation)?

If you search 'set_watershed_boundary_condition_outlet_id' in the index, you'll find [the following page ](https://landlab.readthedocs.io/en/latest/landlab.grid.html#landlab.grid.raster.RasterModelGrid.set_watershed_boundary_condition_outlet_id) that describes how the function works.

**Comment by rbunel** [comment] 2018-09-07 14:48
Thanks @kbarnhart . Among the possible outlets, I defined node 322 as the outlet `set_watershed_boundary_condition_outlet_id`

```python
from landlab.io import read_esri_ascii 
from landlab import CLOSED_BOUNDARY, FIXED_VALUE_BOUNDARY
from landlab import imshow_grid_at_node
from landlab.components import SinkFiller
import numpy as np

watershed_dem ="C:/Users/bunelrap/downloads/dem_landlab.txt"

rmg, z = read_esri_ascii(watershed_dem, name='topographic__elevation')

rmg.set_watershed_boundary_condition(z,nodata_value=-9999.)

rmg.set_watershed_boundary_condition_outlet_id(322, z, -9999.)

sf = SinkFiller(rmg, routing='D4', apply_slope=True)
sf.fill_pits()
```
When I apply SinkFiller, I get the following error:

```python
Traceback (most recent call last):

  File "<ipython-input-21-35d252670b74>", line 2, in <module>
    sf.fill_pits()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 201, in fill_pits
    self.run_one_step(**kwds)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 249, in run_one_step
    lowest_elev_perim = perim_elevs[perim_elevs != out_elev].min()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation minimum which has no identity
```

Here is the dem : 
[dem_landlab.txt](https://github.com/landlab/landlab/files/2361479/dem_landlab.txt)

**Comment by kbarnhart** [comment] 2018-09-07 15:02
@rbunel I'd bring this issue up in Issue #781 instead of here. I'm not an expert at the internals of SinkFiller.

**Comment by nicgaspar** [comment] 2018-09-07 16:11
@rbunel I'm guessing (not sure) that the problem is because you have multiple points in your DEM that have the same elevation as your assigned outlet node (322). That is why `set_watershed_boundary_conditions` was not initially working for you. I'm not sure, but try changing the elevation of nodes 107 319 320 321 to something just a little bit higher. It might work then.

**Comment by rbunel** [comment] 2018-09-07 16:53
Thank you @nicgaspar for your help.

I slightly increased the altitudes of cells 319 320 321 and 322 to have an outlet for cell 107.
This solved the problem related to set_watershed_boundary_conditions well.
But this does not solve the SinkFiller problem with the same error message : 

```python
Traceback (most recent call last):

  File "<ipython-input-47-35d252670b74>", line 2, in <module>
    sf.fill_pits()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 201, in fill_pits
    self.run_one_step(**kwds)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 249, in run_one_step
    lowest_elev_perim = perim_elevs[perim_elevs != out_elev].min()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by nicgaspar** [comment] 2018-09-07 17:03
@rbunel It was just a hunch based on the error. I'm actually not very familiar with the SinkFiller. Maybe put your post up again in issue #781 as @kbarnhart suggested so it can be properly tracked.

**Comment by rbunel** [comment] 2018-09-08 13:01
@kbarnhart To come back to the creation of a D4 flow raster, when I apply this script:

```python
from landlab.io import read_esri_ascii
import numpy as np
from landlab.components import FlowRouter, DepressionFinderAndRouter
from landlab import RasterModelGrid
from landlab.io.esri_ascii import write_esri_ascii

watershed_dem ="C:/Users/bunelrap/downloads/beau_filled2.asc"
rg, z = read_esri_ascii(watershed_dem, name='topographic__elevation')

fr = FlowRouter(rg, method='D4')
fr.run_one_step()

df = DepressionFinderAndRouter(rg, routing='D4')
df.map_depressions()

d4_fd = rg.add_zeros('d4_flow_directions', at='node')

r = rg.at_node['flow__receiver_node']

# East
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,0]] = 1

# North
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,1]] = 64

# West
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,2]] = 16

# South
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,3]] = 4


write_esri_ascii('C:/Users/bunelrap/downloads/d4_fd.asc',rg)

```

 I noticed that all edge cells of the catchment are force to flow outward even when the slopes allow a flow towards the inside of the basin.  Is it possible to define the flow directions at the edges on the basis of the slope gradients and to have a flow towards the outside of the catchment only when all neighbouring cells are higher?

**Comment by SiccarPoint** [comment] 2018-09-10 08:31
There isn't a function for this, but you should be able to do it for yourself. For each of the FIXED_VALUE_BOUNDARY nodes, work out which have a CORE node that is lower as a neighbor, and set those nodes to CORE by hand.

**Comment by rbunel** [comment] 2018-09-10 09:54
Thank you @SiccarPoint 
In fact, the edges of the basin are already defined as cores nodes. The function is therefore able to define a flow direction for these nodes but the problem is that it is systematically oriented towards the outside of the basin.

**Comment by kbarnhart** [comment] 2018-09-10 18:50
@rbunel the flow direction is behaving exactly as I would expect it to given that you have not set the nodes that have values of -9999 as closed nodes. 

Even though your esrii ascii file lists the no-data value as -9999, landlab does not automatically use that information to change the node status of the no-data nodes from CORE to CLOSED. 

You can set the no-data nodes to closed with the command 

```python
rg.set_nodata_nodes_to_closed(z, -9999)
```

immediately after importing your DEM. This is one of the things that happens in the `set_watershed_boundary_conditions`-type methods. 

As you haven't set those nodes to closed, the nodes at the edge of the watershed are flowing to the steepest downhill node, which happens to be the no-data node with an elevation of -9999.

After setting the no data nodes to closed, calculating the flow directions and making a plot, I get something like this:

![flow_dir_d4_bc](https://user-images.githubusercontent.com/6589339/45317451-460d5200-b4f7-11e8-9f8f-dd9453bdb12b.png)

Which I expect is what you expect. 

When I have issues with boundary conditions, I often find it useful to make the following plot:

```python
imshow_grid(rg, rg.status_at_node)
```

As many of the questions you are asking relate to boundary conditions and grid definitions, I'd recommend you review the [Hobley et al](https://www.earth-surf-dynam.net/5/21/2017/esurf-5-21-2017.html) paper that goes over landlab boundary conditions, the [portions of the wiki that describe setting grid boundary conditions](https://github.com/landlab/landlab/wiki/Grid#managing-grid-boundaries), and these two tutorials:  [reading a raster into landlab](https://github.com/landlab/tutorials/blob/release/reading_dem_into_landlab/reading_dem_into_landlab.ipynb) and [watershed boundary conditions](https://nbviewer.jupyter.org/github/landlab/tutorials/blob/release/boundary_conds/set_watershed_BCs_raster.ipynb).

I'd recommend you consider if it makes sense for setting a halo value when you import your DEM as well -- this will depend on if you have data nodes on the model grid boundary.

**Comment by rbunel** [comment] 2018-09-11 08:51
Thank you very much @kbarnhart for this very detailed answer and references.

This time I think I have correctly specified the boundary conditions with CORE_NODE (type 0) for nodes inside the catchment, FIXED_VALUE_BOUNDARY (Type 1) for the halo cell that is just below the outlet and CLOSED_BOUNDARY (Type 4) for all other -9999 cells . 

```python
watershed_dem ="C:/Users/bunelrap/downloads/dem_landlab.txt"

rg, z = read_esri_ascii(watershed_dem, name='topographic__elevation',halo=1)

rg.set_nodata_nodes_to_closed(rg.at_node['topographic__elevation'],-9999)

open_nodes = np.where(rg.status_at_node != CLOSED_BOUNDARY)[0]
min_open = z[open_nodes].argmin()
min_node_ID = open_nodes[min_open]
rg.status_at_node[min_node_ID-rg.number_of_node_columns] = FIXED_VALUE_BOUNDARY

#sf = SinkFiller(rg, routing='D4', apply_slope=True)
sf = SinkFiller(rg, routing='D4', apply_slope=False)
sf.fill_pits()

fr = FlowRouter(rg, method='D4')
fr.run_one_step()

df = DepressionFinderAndRouter(rg, routing='D4')
df.map_depressions()

d4_fd = rg.add_zeros('d4_flow_directions', at='node')

r = rg.at_node['flow__receiver_node']

# East
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,0]] = 1

# North
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,1]] = 64

# West
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,2]] = 16

# South
rg.at_node['d4_flow_directions'][r == rg.neighbors_at_node[:,3]] = 4

from landlab.io.esri_ascii import write_esri_ascii
write_esri_ascii('C:/Users/bunelrap/downloads/d4_fd.asc',rg)

```

And I manage to get what I want in terms of flow directions.

The last remaining problem relates to SinkFiller, which although the boundary conditions are I think correctly specified, always produces the following error only when I try to apply a slope to flat areas (apply_slope=True) :

```python
Traceback (most recent call last):

  File "<ipython-input-121-055d21856cfa>", line 26, in <module>
    sf.fill_pits()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 201, in fill_pits
    self.run_one_step(**kwds)

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\landlab\components\sink_fill\fill_sinks.py", line 249, in run_one_step
    lowest_elev_perim = perim_elevs[perim_elevs != out_elev].min()

  File "C:\Users\bunelrap\AppData\Local\Continuum\anaconda2\lib\site-packages\numpy\core\_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)

ValueError: zero-size array to reduction operation minimum which has no identity
```
I also report the error on issue #781.
I'll come back to you if I can find a solution. Thank you all for your help and time.

**Comment by kbarnhart** [comment] 2018-09-11 14:35
@rbunel glad that this helped. Feel free to close the issue whenever you feel like you've gotten all the information you need. 

Asking questions about the SinkFiller on #781 is definitely the right place. Sorry that I can't be more helpful there, its not something I developed or use much. 

I'd recommend that you stop using the FlowRouter and use the FlowAccumulator instead. The FlowAccumulator does everything done by the FlowRouter and more and was designed to replace it.

**Closed** 2018-09-11 14:55 UTC
Labels: help wanted, question
