### ISSUE TITLE
write.netcdf

### ISSUE THREAD

**Issue by brigidlynch** [landlab/landlab#90] opened 2015-02-11 23:59 UTC
I'm trying to use write.netcdf to get drainage area out of a driver I have built but get this error. 

"ValueError: NetCDF 3 does not support type int64"

when I do get a netcdf file out it contains x and y coordinates and k_values but not the other two variables in the RasterModelGrid (topographic elevation or drainage area).

**Comment by mcflugen** [comment] 2015-02-12 00:14
@brigidlynch, would it be possible to supply a code snippet that reproduces the problem? It would be useful for debugging.

Two possible solutions:
* Use netcdf4, which, I think, supports 64-bit integers. To do this, you need to make sure the netcdf4 Python package is installed.
* Make sure your data are all floats. Can you verify that, indeed, all your data are floats? If not, do you require integers?

**Comment by brigidlynch** [comment] 2015-02-12 01:12
Thanks, 
I'll work on installing the netcdf4 package but we've had issues trying to install it in the past. At the end of the code below I was trying to make the data floats but I'm not sure if I was successful. 


Here's the code for the driver: 

from landlab.components.flow_routing.route_flow_dn import FlowRouter
from landlab.components.stream_power.stream_power import StreamPowerEroder
from landlab.components.nonlinear_diffusion.Perron_nl_diffuse import PerronNLDiffuse
from landlab.components.diffusion.diffusion import DiffusionComponent #the two different diffusion formulations
import os #to manipulate path names
import time #timekeeping
import numpy as np #numerical operations
import pylab #to plot results
from landlab import RasterModelGrid #import grid class
from landlab import ModelParameterDictionary #handles input from input file
from landlab.plot.imshow import imshow_node_grid
from landlab.io import read_esri_ascii #to import DEM
from landlab.io.netcdf import write_netcdf
from landlab.plot.imshow import imshow_node_grid 

#get needed properties to build grid:
input_file = 'driver1_params.txt'

#initialize an object that will supply the parameters:
inputs = ModelParameterDictionary(input_file) #sp
nrows = inputs.read_int('nrows') #sp
ncols = inputs.read_int('ncols') #sp
dx = inputs.read_float('dx') #sp
dt = inputs.read_float('dt') #sp
run_time = inputs.read_float('run_time') #sp/diffusion
uplift = inputs.read_float('uplift_rate') #sp
init_elev = inputs.read_float('init_elev') #sp
#leftmost_elev = inputs.read_float('leftmost_elevation') #diffusion_driver
initial_slope = inputs.read_float('initial_slope') #diffusion_driver
nt = int(run_time//dt) #divide and truncate (number of timesteps) diffusion_driver

#Instatiate the grid object
mg = RasterModelGrid(nrows, ncols, dx) 

#create the fields in the grid
mg.create_node_array_zeros('topographic_elevation')
z = mg.create_node_array_zeros() + init_elev
mg['node']['topographic_elevation'] = z + np.random.rand(len(z))
mg.create_node_array_zeros('drainage_area')
a = mg.create_node_array_zeros() 
mg['node']['drainage_area'] = a + np.random.rand(len(a))
#ar = mg.node_vector_to_raster(mg['node']['drainage_area'])

#set boundary conditions
mg.set_fixed_value_boundaries_at_grid_edges(True, True, True, True) #diffusion driver

#make some K values in a field to test 
mg.at_node['K_values'] = 0.1+np.random.rand(nrows*ncols)/10.

print( 'Running ...' )
time_on = time.time()

#instantiate the components:
fr = FlowRouter(mg)
sp = StreamPowerEroder(mg, input_file)
diffuse = PerronNLDiffuse(mg, input_file)
lin_diffuse = DiffusionComponent(grid=mg, input_stream=input_file)

#perform the loop

uplifted_nodes = mg.get_core_nodes() #perform block uplift of interior of grid, leave boundary nodes at original elevations
    
#stream power loop
elapsed_time = 0. #total time in simulation
while elapsed_time < run_time:
    print elapsed_time
    if elapsed_time+dt>run_time:
        print "Short step!"
        dt = run_time - elapsed_time
    mg = fr.route_flow(grid=mg)
    mg,_,_ = sp.erode(mg, dt, node_drainage_areas='drainage_area', slopes_at_nodes= 'steepest_slope', K_if_used='K_values')
    #add uplift
    mg.at_node['topographic_elevation'][mg.core_nodes] +=uplift*dt
    elapsed_time += dt
    
    #diffusion driver loop
    for i in xrange(nt): # loop nt times, xrange is clever memory-saving way of prodcing consecutive integers to govern a loop)
    #this line performs functionality of componen,swap between these two
        mg = lin_diffuse.diffuse(mg, i*dt) #linear diffusion
        #mg = diffuse.diffuse(mg, i*dt) #nonlinear diffusion
        #mg = fr.route_flow(grid=mg)
        #mg = sp.erode(mg, dt, 'drainage_area') #how can i get these to work...
        
    #plot N-S cross section from this stage in the run onto figure 1. 
    pylab.figure(1)
    elev_r = mg.node_vector_to_raster(mg['node']['topographic_elevation']) #turn the 1-D array of elevation values 
        #into a spatially accurate 2-D gridded format, for plotting
    drainage_area = mg.node_vector_to_raster(mg['node']['drainage_area'])
    im = pylab.plot(mg.dx*np.arange(nrows), elev_r[:,int(ncols//2)])
    im = pylab.plot(mg.dx*np.arange(nrows), drainage_area[:,int(ncols//2)])
        #square brackets: subset of nodes to use
        #this type of data extraction from a larger data structure is called slicing/ fancy indexing 
time_off = time.time()
print 'Elapsed time: ', time_off-time_on

#Finalize and plot
elev = mg['node']['topographic_elevation']
evel_r = mg.node_vector_to_raster(elev) 
drain_a = mg['node']['drainage_area']
drainage_area = mg.node_vector_to_raster(drain_a)

#Clear previous plots
pylab.figure(1)
pylab.close()

#Plot topography
pylab.figure(1)
im = imshow_node_grid(mg, 'topographic_elevation') #display a colored image
print elev_r

pylab.figure(2)
im = pylab.plot(dx*np.arange(nrows), elev_r[:,int(ncols//2)]) #display a colored image
pylab.title('Vertical Cross Section')

pylab.figure(3)
im = imshow_node_grid(mg, 'drainage_area')
pylab.show()
mg=mg['node']['drainage_area'].astype(float)
mg=mg['node']['topographic_elevation'].astype(float)
write_netcdf('drainage_area.nc', mg)

**Comment by mcflugen** [comment] 2015-02-12 01:19
Thanks!

I'll need your input files, too (maybe it's just `driver1_params.txt`?). Is it small enough to paste here?

**Comment by brigidlynch** [comment] 2015-02-12 18:07
#These values are for building the grid-
nrows:
100
ncols:
100
dx:
1.
dt:
1.
uplift_rate: #per time, not per timestep
0.001
run_time:
2.
init_elev:
0.
initial_slope:
0.

#These values are for running the process-
rock_density:
2.7
sed_density:
2.7
K_sp:
array
#0.5
m_sp:
0.5
n_sp:
1.
threshold_sp:
0.
#use_Q:
#True

#nonlinear diffuser: 
kappa:
0.01
S_crit:
0.56

#linear diffuser:
DIFMOD_KD:
0.01

**Comment by mcflugen** [comment] 2015-02-12 18:43
I see the problem. One of the components you are using is creating a bunch of new fields and storing them in your `RasterModelGrid`. Some of these fields contain values that are of type `int64`. The full list of fields contained in you grid are:
* K_values (double)
* flow_receiver (int64)
* upstream_ID_order (int64)
* water_discharges (double)
* stream_power_erosion (double)
* topographic_elevation (double)
* flow_sinks (byte or boolean)
* drainage_area (double)
* steepest_slope (double)
* links_to_flow_receiver (int64)

I assume you aren't interested in any of these fields apart from *drainage_area* and *topographic_elevation*, is that correct?

The are a couple of solutions:

* Install the netcdf4 package and then call `write_netcdf` and set the *format* keyword to that string `NETCDF4`. Because netcdf4 supports `int64`, you'll be able to create a netcdf file with all of the above fields. However, to get that to work I had to make a couple small changes to the code so you will have to pull the most recent version from the repository.

* I'll add a *fields* keyword to `write_netcdf` that will take a list of names of fields to write. Thus, you would write to netcdf with something like,
```python
write_netcdf('drainage_area.nc', mg, fields=('drainage_area', 'topographic_elevation'))
```
Since those fields are of type `float` you don't need to use netcdf4.

So try the first solution and I'll work on adding the *fields* keyword to `write_netcdf`.

**Comment by brigidlynch** [comment] 2015-02-12 21:25
Thanks for the help, I'll work on getting netcfd4 and see how that goes.

**Comment by mcflugen** [comment] 2015-02-14 21:30
@brigidlynch, I've added a *names* keyword to `write_netcdf` that allows you to specify a list of data fields to include in your netcdf file. This should allow you to only write the fields you want, which are all floats. This allows you to write to netcdf3, as long as the fields you want to write are not `int64`.

I've also expanded the documentation and added an example for [write_netcdf](http://landlab.readthedocs.org/en/latest/manual_index_alt_format.html?highlight=write_netcdf#landlab.io.netcdf.write.write_netcdf) to include this new keyword.

For your case, the following should do the trick,
```python
write_netcdf('drainage_area.nc', mg, names=('drainage_area', 'topographic_elevation'))
```

**Comment by brigidlynch** [comment] 2015-02-17 20:41
Thanks so much for working on this, unfortunately I'm getting some errors when implementing that code into my driver. When inputing the command you gave me I get: 
```
TypeError                                 Traceback (most recent call last)
/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/Users/blynch/Research/Working_Directories/driver_bml/driver2_bml.py in <module>()
    132 ag=mg['node']['drainage_area'].astype(float)
    133 mg=mg['node']['topographic_elevation'].astype(float)
--> 134 write_netcdf('drainage_area.nc', mg, names=('drainage_area', 'topographic_elevation'))
    135 
    136 #mg.at_node['drainage_area'])

TypeError: write_netcdf() got an unexpected keyword argument 'names' 
```
I was expecting to get an error in the write.py file before the driver error so I wasn't quite sure how to debug this. 
I worked with Brian a bit and we attempted to get all variables in the grid out rather than just drainage area and elevation which then gives us this..
``` 
AttributeError                            Traceback (most recent call last)
/Applications/Canopy.app/appdata/canopy-1.4.1.1975.macosx-x86_64/Canopy.app/Contents/lib/python2.7/site-packages/IPython/utils/py3compat.pyc in execfile(fname, *where)
    202             else:
    203                 filename = fname
--> 204             __builtin__.execfile(filename, *where)

/Users/blynch/Research/Working_Directories/driver_bml/driver2_bml.py in <module>()
    132 ag=mg['node']['drainage_area'].astype(float)
    133 mg=mg['node']['topographic_elevation'].astype(float)
--> 134 write_netcdf('drainage_area.nc', ag, format='NETCDF3_64BIT')
    135 
    136 #mg.at_node['drainage_area'])

/Users/blynch/Research/Working_Directories/landlab/landlab/io/netcdf/write.pyc in write_netcdf(path, fields, attrs, append, format)
    189     Parameters
    190     ----------
--> 191     path : str
    192         Path to output file.
    193     fields : field-like

/Users/blynch/Research/Working_Directories/landlab/landlab/io/netcdf/write.pyc in _set_netcdf_variables(root, fields, **kwds)
     73 
     74     First set the variables that define the grid and then the variables at
---> 75     the grid nodes and cells.
     76     """
     77     names = kwds.pop('names', None)

/Users/blynch/Research/Working_Directories/landlab/landlab/io/netcdf/write.pyc in _add_spatial_variables(root, grid, **kwds)
     96 
     97     spatial_variable_names = _get_axes_names(grid.shape)
---> 98     spatial_variable_shape = _get_dimension_names(grid.shape)
     99 
    100     for (axis, name) in enumerate(spatial_variable_names):

AttributeError: 'numpy.ndarray' object has no attribute 'node_axis_coordinates'

```
We're thinking there's something going on in the write.py file but struggling to follow the code to figure it out. So sorry to be taking up your time with this but I really appreciate the help!

**Comment by mcflugen** [comment] 2015-02-17 20:57
It looks like you're still using an old version of landlab. Did you pull the latest version from GitHub? After getting the new version of the code, depending on how you installed landlab previously, you may need to reinstall it.

I think you also need to remove lines 132 and 133 from your script. Line 133, in particular, looks problematic. In it, you're assigning a numpy array to `mg` but then using `mg` in the following line as though it is a `RasterModelGrid`.

**Comment by gregtucker** [comment] 2015-07-25 18:29
Brigid, Eric,
I ran into this problem too today. I didn't need 64-bit integers---my data array has only 0's and 1's. I could maybe have tried a binary field, but instead went with numpy's type uint8, which seems to work fine with NetCDF 3:

some_field = mg.add_zeros('node', 'my_field', dtype=numpy.uint8)

**Comment by mcflugen** [comment] 2015-08-05 20:53
I'm going to close this since netcdf3 doesn't support `int64` arrays, which is beyond our control.

@gregtucker, I don't believe either netcdf3 or netcdf4 supports binary arrays. As you say, they both support `uint8` arrays, though. However, I notice that the netcdf3 writer (from *scipy*) writes `uint8` arrays as string arrays, which isn't great and a little confusing to read back in.

**Closed by mcflugen** 2015-08-05 20:53 UTC
Labels: bug
