### ISSUE TITLE
Memory leak in LakeMapperBarnes

### ISSUE THREAD

**Issue by DavidLitwin** [landlab/landlab#1156] opened 2020-02-26 16:03 UTC
I'm running the lake mapper in a landscape evolution model in order to route flow through depressions, particularly those that occur because of the randomized initial condition. I found that the HPC node I am using was consistently running out of memory, and I have narrowed down the source of this memory use increase to the lake mapper. 

Attached is a minimal reproducible example, with a plot showing how memory usage increases linearly with iteration in a for loop. Any support on this would be helpful. I would like to get this up and running soon.

[lake_mapper_mem.zip](https://github.com/landlab/landlab/files/4256769/lake_mapper_mem.zip)

**Comment by kbarnhart** [comment] 2020-02-26 17:07
@DavidLitwin thanks for bringing this up. @SiccarPoint is really the correct person to get help from since he made this component.

**Comment by SiccarPoint** [comment] 2020-02-28 15:05
I have some bad news for you, I'm afraid. This is a fundamental Python problem, and not one we can easily code our way out of. Python doesn't have a built in mechanism to release memory blocks once they are used. I've hit this problem previously in other components, where if you hammer away for long enough on a complex component that needs to do calculations involving building arrays of different and unpredictable lengths, your system will run out of memory and crash. I know your pain here: watching Python throw a memory allocation error is a disconcerting experience to say the least. The issue is one of dynamically allocated arrays of differing sizes, which is an inevitable feature of the way this component works.

There is unfortunately no easy fix for this. A full component redesign would be needed such that all arrays are reallocated into existing memory, which is a nightmare to do, as Python is explicitly designed to stop you needing to do this kind of management. And even then, I'm not convinced this would solve the problem. I've tried something like this in the past and it never stopped the leak completely. If you're feeling brave, you can try this yourself by finding anywhere where a Python list or array is created without a fixed length, and turning it into a nnodes-length array where only the first x entries hold the current data alongside a tracking int that tells you how long the array "actually" is at any given time. I'm unlikely to have the time for this any time particularly soon, sorry.

The hacky fix is to avoid calling the component a lot of times within the same python session if at all possible. Building a unix script to call Python instances sequentially will work if you can figure it out for your use case, since the memory gets released once Python itself terminates a session (and not before, unfortunately). Alternatively, try the other LakeMapper again. Some time before Christmas, I managed to get something approaching a 100-fold (!) acceleration out of it through some , so if you haven't looked at in in a while you might be pleasantly surprised. However, that said, I have a nasty suspicion that this component will suffer the exact same problem you're highlighting here. Repeated allocation of arrays with unpredicable lengths is something of a common feature to many lake fill algorithms.

I'll take a bit of time ASAP to check I've diagnosed this right, but I'm afraid I am not optimistic.

**Comment by DavidLitwin** [comment] 2020-02-28 15:55
Thank you for the detailed description! I'm not sure this is the kind of problem that I have the time or expertise to work on myself. With what is currently available it seems like the trick in a landscape evolution model context is to have erosion remove all pits from the original surface (and thus be able to stop running the component) long before running out of memory. 

I merged your fall 2019 updates on the other LakeMapper into a branch I was working on at the time and it was much faster! But I've since made other changes to my code, and now I think what I'm waiting for there is integration with Landlab 2.0. I'm not exactly sure what needs to happen there, but the last time I checked, because the location of some of the flow routing and accumulation tools were moved around, I was unsure how to make this integration myself. I mentioned this briefly in #1040. 

Out of curiosity, could any of these problems be managed more easily in cython? Or is this likely to be inevitable there too?

**Comment by gregtucker** [comment] 2020-02-28 16:12
Two thoughts: (1) all the components should be up to speed with Landlab 2.0, so if there's a problem, we should track it down pronto; (2) one strategy would be to pre-allocate necessary arrays and keep them throughout the component's existence.

**Comment by DavidLitwin** [comment] 2020-02-28 16:16
@gregtucker, (and @SiccarPoint, correct me if I'm wrong) I think the issue is that the pull request with that speed update was never merged into 1.0. I merged the updates into a branch I was working on just to get something running. This is how I produced my AGU results! So now that branch is out of date (see #1040) and would need some work to be merged into 2.0.

**Comment by SiccarPoint** [comment] 2020-02-28 16:19
I'm on this. Fixing the merge isn't a big deal I don't think.

**Comment by SiccarPoint** [comment] 2020-02-28 16:23
@gregtucker Yes, that strategy *should* work. But based on past experience, that's easier said than done. I brief read online suggests that actually diagnosing the problem in detail is likely to be very time consuming. Will take a look early next week, but not super optimistic...

**Comment by DavidLitwin** [comment] 2020-03-03 18:55
Alright, I have good news and bad news. The good news is that the cythonized version of the DepressionFinderAndRouter (#1040) is faster than the previous version, and doesn't have a memory leak problem seen in LakeMapperBarnes. If you are curious, I've attached some examples.

The bad news is that it is still significantly slower than LakeMapperBarnes, at least for the grid size that I'm using (100x100). For a surface with random noise, the flow accumulation + cythonized DepressionFinderAndRouter is running about 0.5-0.9 sec per iteration, while flow accumulation + LakeMapperBarnes is running about 0.1-0.2 sec per iteration. 

@gregtucker and @SiccarPoint, I like this pre-allocating idea, if it is possible. What do you think?

[depression_finder_mem.zip](https://github.com/landlab/landlab/files/4283035/depression_finder_mem.zip)

**Comment by SiccarPoint** [comment] 2020-03-04 09:42
The efficient way to do this will be to find where the leak is (i.e., which func) and fix only that one. This will result in a lot less pain in the long run...

**Comment by SiccarPoint** [comment] 2020-03-04 10:40
I solved it! And pretty pleased with myself too.

The issue is in the use of heaps (and presumably deques as well) in Python. Following general Landlab practice, we preallocate these heap structures on init of the component so they are accessible in principle from any where in the component and also externally, i.e.,  `self._open = StablePriorityQueue()` in this case. However, this means that the heap now exists in a high level scope within the component, and so ''will never get garbage collected''. So, even if `self._open` appears to be empty in between calls to `run_one_step`, the memory it has previously consumed while longer (as `run_one_step` executes) is never released. Ironically then, the problem is the exact inverse of what you might expect (and the instinctive diagnosis Greg and I went to) - preallocation of arrays is killing us here, not making the problem better.

The solution here is fairly trivial - if we move the declaration of the `_open` variable down to ''within'' `run_one_step`, then every time `run_one_step` is called and completes, the memory is freed and garbage collection can take care of it. The downside is that other parts of the component can no longer see the `_open` variable. In this case, this isn't too problematic - but it could be a total pain in other similar components.

Learned lesson: never preallocate an object with extremely variable length during component `__init__`. This will be - and probably already is - an issue elsewhere in the code base, but a relatively easy fix here.

**Comment by SiccarPoint** [comment] 2020-03-04 10:42
Although the fix is easy, making it has trashed the tests on this component. Now fixing...

**Comment by DavidLitwin** [comment] 2020-03-04 13:45
@SiccarPoint Thank you for sorting this out! It does make sense that keeping the heap around by initializing it with the component would create a problem for garbage collection. I've read that garbage collection can be resource intensive, which makes me wonder if performance will be slightly lower now that the memory leak is resolved. I will check, but in either case, having something that can be run safely in a for loop will be worth it.

**Closed** 2020-03-04 16:15 UTC
Labels: bug
