### ISSUE TITLE
ErosionDeposition example does not work

### ISSUE THREAD

**Issue by PxGhosh** [landlab/landlab#762] opened 2018-07-25 05:41 UTC
The example of ErosionDeposition component given in LandLab docs.
http://landlab.readthedocs.io/en/release/landlab.components.erosion_deposition.html
does not work.
The problem lays with the way E/D has been instantiated, i.e.,
ed = ErosionDeposition(mg, K=0.00001, phi=0.0, v_s=0.001,
                       m_sp=0.5, n_sp = 1.0, sp_crit=0,
                       method='simple_stream_power',
                       discharge_method=None, area_field=None,
                       discharge_field=None)

However, it works if it done the following way.

ed = ErosionDeposition(mg, K=0.00001, phi=0.0, v_s=0.001,
                       m_sp=0.5, n_sp = 1.0, sp_crit=0,
                       method='simple_stream_power',
                       discharge_method='discharge_field', area_field=None,
                       discharge_field='surface_water__discharge')

I hope this is the right way to correct the code.

I am using Windows 10 Pro 64 bit. The trace of the error is given below.

Traceback (most recent call last):

  File "<ipython-input-1-b8f89cb6bfff>", line 1, in <module>
    runfile('E:/LandlabModels/LandModel3.py', wdir='E:/LandlabModels')

  File "E:\WinPythonInstalled\python-3.6.5.amd64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "E:\WinPythonInstalled\python-3.6.5.amd64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "E:/LandlabModels/LandModel3.py", line 64, in <module>
    ed.run_one_step(dt = ed_dt, flooded_nodes=flooded)

  File "E:\WinPythonInstalled\python-3.6.5.amd64\lib\site-packages\landlab\components\erosion_deposition\erosion_deposition.py", line 221, in run_one_step_basic
    self._calc_hydrology()

  File "E:\WinPythonInstalled\python-3.6.5.amd64\lib\site-packages\landlab\components\erosion_deposition\generalized_erosion_deposition.py", line 168, in _calc_hydrology
    self.Q_to_the_m[:] = np.power(self.q, self.m_sp)

TypeError: unsupported operand type(s) for ** or pow(): 'NoneType' and 'float'

**Comment by kbarnhart** [comment] 2018-07-25 12:51
@PxGhosh thanks for raising this issue.

After looking into this, I've identified that the problem is that the docs are not currently building (identified in Issue #734). Thus you are looking at an outdated version of the docs. 

@gregtucker , @cmshobe , and I did an overhaul of the internals of the ErosionDeposition and SPACE components to address Issue #708 and the improvements are in the current release version.  Based on your traceback, I can see that you are using the latest version of ErosionDeposition and SPACE.

 @mcflugen lets discuss the best way to fix the docs on the thread at Issue #734. @PxGhosh , once we fix the docs, I'll make a note here and close this issue. 

In the meantime, I'd recommend you look directly at the ErosionDeposition docstring (which is where the documentation is autogenerated from. (The code is here)[https://github.com/landlab/landlab/blob/release/landlab/components/erosion_deposition/erosion_deposition.py], and you'll want to start with lines 69-175.

**Comment by PxGhosh** [comment] 2018-07-27 12:30
I thank all of you for taking up this issue. I am new to Git and I hope that I should reply using Git and not by replying to the e-mails. Please correct me if I am wrong. Also, should I choose "Close and comment" or simply "comment"?

**Comment by kbarnhart** [comment] 2018-09-19 01:28
@PxGhosh the docs have now been fixed in both the `master` and `release` branch. I'll close this issue now. Feel free to re-open it if you need or open a new one.

**Closed by kbarnhart** 2018-09-19 01:29 UTC

**Comment by PxGhosh** [comment] 2018-09-19 19:15
Thank you very much. Have a good day.

⁣Sent from BlueMail ​
