### ISSUE TITLE
Tests fail for developers installation

### ISSUE THREAD

**Issue by glaubius** [landlab/landlab#486] opened 2017-05-31 16:29 UTC
I'm using Mac OS  Sierra 10.12.5 and Anaconda 3. 
Here's what I get when I run landlab.test():
```
landlab version 1.0.2
landlab is installed in /Users/jenglaubius/Landlab/landlab/landlab
Python version 3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
nose version 1.3.7
Running unit tests and doctests for landlab
NumPy version 1.12.1
NumPy relaxed strides checking option: True
NumPy is installed in /Users/jenglaubius/anaconda/lib/python3.5/site-packages/numpy
Python version 3.5.3 |Anaconda custom (x86_64)| (default, Mar  6 2017, 12:15:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
nose version 1.3.7
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module
Missing member or type mismatch for __init__
Missing member or type mismatch for __init__
/Users/jenglaubius/Landlab/landlab/landlab/bmi/bmi_bridge.py:1: PendingDeprecationWarning: generator '__iter__' raised StopIteration
  """
.........................../Users/jenglaubius/Landlab/landlab/landlab/components/chi_index/channel_chi.py:211: RuntimeWarning: divide by zero encountered in true_divide
  chi_integrand = (A0/valid_upstr_areas)**reftheta
............................................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calc_grad_of_active_link.
  name=func.__name__), category=DeprecationWarning)
/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calc_grad_at_active_link.
  name=func.__name__), category=DeprecationWarning)
.FlowAccumulator found both the field 'water__unit_flux_in' and a provided float or array for the runoff_rate argument. THE FIELD IS BEING OVERWRITTEN WITH THE SUPPLIED RUNOFF_RATE!
................................/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:145: DeprecationWarning: Passing a file to a component's __init__ method is deprecated. Instead, pass parameters as keywords.
  category=DeprecationWarning)
FlowAccumulator found both the field 'water__unit_flux_in' and a provided float or array for the runoff_rate argument. THE FIELD IS BEING OVERWRITTEN WITH THE SUPPLIED RUNOFF_RATE!
.FlowAccumulator found both the field 'water__unit_flux_in' and a provided float or array for the runoff_rate argument. THE FIELD IS BEING OVERWRITTEN WITH THE SUPPLIED RUNOFF_RATE!
..../Users/jenglaubius/Landlab/landlab/landlab/components/flow_routing/route_flow_dn.py:159: DeprecationWarning: 'method' should be set at initialization now. Please update your code.
  "Please update your code.", DeprecationWarning)
....................../Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  
/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py:2: DeprecationWarning: This function is deprecated. Please call randint(30, 900 + 1) instead
  # %% Import Libraries
/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py:2: DeprecationWarning: This function is deprecated. Please call randint(5, 20 + 1) instead
  # %% Import Libraries
/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py:2: DeprecationWarning: This function is deprecated. Please call randint(26, 40 + 1) instead
  # %% Import Libraries
/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py:2: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  # %% Import Libraries
F....................../Users/jenglaubius/Landlab/landlab/landlab/components/overland_flow/generate_overland_flow_Bates.py:205: RuntimeWarning: invalid value encountered in true_divide
  abs(self.q[self.active_links]) / hflow ** self.ten_thirds))
....../Users/jenglaubius/Landlab/landlab/landlab/components/overland_flow/generate_overland_flow_deAlmeida.py:492: RuntimeWarning: invalid value encountered in true_divide
  self.h_links[vert] ** _SEVEN_OVER_THREE))
.............................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calculate_slope_aspect_at_nodes_burrough.
  name=func.__name__), category=DeprecationWarning)
...................../Users/jenglaubius/Landlab/landlab/landlab/components/soil_moisture/infiltrate_soil_green_ampt.py:270: DeprecationWarning: assignment will raise an error in the future, most likely because your index result shape does not match the value array shape. You can use `arr.flat[index] = values` to keep the old behaviour.
  self.i_act[full_infil_indx] = (self._water_depth) - self._lilwater
......................./Users/jenglaubius/Landlab/landlab/landlab/components/stream_power/sed_flux_dep_incision.py:381: UserWarning: Found no incision threshold to use.
  warnings.warn("Found no incision threshold to use.")
..................................../Users/jenglaubius/Landlab/landlab/landlab/core/utils.py:114: DeprecationWarning: Assigning the 'data' attribute is an inherently unsafe operation and will be removed in the future.
  x.data = extended.data
............................................................................................................................../Users/jenglaubius/Landlab/landlab/landlab/graph/object/at_node.py:140: UserWarning: input must be ndarray of int for in-place sort
  warnings.warn('input must be ndarray of int for in-place sort')
......................................................................................................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function link_unit_vec_x.
  name=func.__name__), category=DeprecationWarning)
/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function link_unit_vec_y.
  name=func.__name__), category=DeprecationWarning)
/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function node_unit_vector_sum_x.
  name=func.__name__), category=DeprecationWarning)
/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function node_unit_vector_sum_y.
  name=func.__name__), category=DeprecationWarning)
......./Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function active_link_connecting_node_pair.
  name=func.__name__), category=DeprecationWarning)
............../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calculate_flux_divergence_at_core_nodes.
  name=func.__name__), category=DeprecationWarning)
/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calculate_flux_divergence_at_nodes.
  name=func.__name__), category=DeprecationWarning)
...................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function max_of_link_end_node_values.
  name=func.__name__), category=DeprecationWarning)
................................/Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function set_nodata_nodes_to_inactive.
  name=func.__name__), category=DeprecationWarning)
...................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function set_inactive_boundaries.
  name=func.__name__), category=DeprecationWarning)
...................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calculate_diff_at_links.
  name=func.__name__), category=DeprecationWarning)
./Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calculate_gradients_at_faces.
  name=func.__name__), category=DeprecationWarning)
.............../Users/jenglaubius/Landlab/landlab/landlab/grid/mappers.py:992: RuntimeWarning: invalid value encountered in true_divide
  np.divide(total_vals, link_count, out=out)
............../Users/jenglaubius/Landlab/landlab/landlab/grid/mappers.py:916: RuntimeWarning: invalid value encountered in true_divide
  np.divide(total_vals, link_count, out=out)
....................................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function face_connecting_cell_pair.
  name=func.__name__), category=DeprecationWarning)
.........../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function node_spacing.
  name=func.__name__), category=DeprecationWarning)
.........................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function has_boundary_neighbor.
  name=func.__name__), category=DeprecationWarning)
........../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calc_slope_aspect_of_nodes_horn.
  name=func.__name__), category=DeprecationWarning)
........./Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function corner_nodes.
  name=func.__name__), category=DeprecationWarning)
....../Users/jenglaubius/Landlab/landlab/landlab/grid/raster_gradients.py:440: MaskedArrayFutureWarning: setting an item on a masked array which has a shared mask will not copy the mask and also change the original mask array in the future.
Check the NumPy 1.11 release notes for more information.
  out[:, (0, 2)] /= grid.dx
....................../Users/jenglaubius/Landlab/landlab/landlab/grid/base.py:3196: UserWarning: 
                  Remember, fixed_links are dominant over node statuses.
                  Your grid may have had an incompatibility between
                  fixed_links and closed nodes, which has been resolved by
                  converting the closed nodes to fixed gradient nodes. If
                  you were trying to deliberately close a node which had
                  once been set to fixed gradient, you need to open the
                  links before changing the node statuses. If you were
                  setting a node to fixed_value, you can ignore this
                  message.
                  
  """)
....................................................................................................................................................................................../Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function calculate_diff_at_active_links.
  name=func.__name__), category=DeprecationWarning)
................................................................................................................................................./Users/jenglaubius/Landlab/landlab/landlab/utils/decorators.py:340: DeprecationWarning: Call to deprecated function set_closed_nodes.
  name=func.__name__), category=DeprecationWarning)
................................................................................................................................................................................................................................................................................................................................................
======================================================================
FAIL: Doctest: landlab.components.landslides.landslide.LandslideProbability
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jenglaubius/anaconda/lib/python3.5/doctest.py", line 2190, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for landlab.components.landslides.landslide.LandslideProbability
  File "/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py", line 11, in LandslideProbability

----------------------------------------------------------------------
File "/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py", line 110, in landlab.components.landslides.landslide.LandslideProbability
Failed example:
    LS_prob.calculate_landslide_probability()
Exception raised:
    Traceback (most recent call last):
      File "/Users/jenglaubius/anaconda/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest landlab.components.landslides.landslide.LandslideProbability[24]>", line 1, in <module>
        LS_prob.calculate_landslide_probability()
      File "/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py", line 353, in calculate_landslide_probability
        [self.grid.number_of_nodes, self.n], dtype='float')
      File "/Users/jenglaubius/anaconda/lib/python3.5/site-packages/numpy/core/numeric.py", line 192, in ones
        a = empty(shape, dtype, order)
    TypeError: 'float' object cannot be interpreted as an integer
----------------------------------------------------------------------
File "/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py", line 111, in landlab.components.landslides.landslide.LandslideProbability
Failed example:
    np.allclose(grid.at_node['landslide__probability_of_failure'], 0.)
Expected:
    False
Got:
    True
----------------------------------------------------------------------
File "/Users/jenglaubius/Landlab/landlab/landlab/components/landslides/landslide.py", line 114, in landlab.components.landslides.landslide.LandslideProbability
Failed example:
    isinstance(LS_prob.landslide__factor_of_safety_histogram[
         core_nodes[0]], np.ndarray) == True
Exception raised:
    Traceback (most recent call last):
      File "/Users/jenglaubius/anaconda/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest landlab.components.landslides.landslide.LandslideProbability[27]>", line 1, in <module>
        isinstance(LS_prob.landslide__factor_of_safety_histogram[
    AttributeError: 'LandslideProbability' object has no attribute 'landslide__factor_of_safety_histogram'

>>  raise self.failureException(self.format_failure(<_io.StringIO object at 0x11defe5e8>.getvalue()))
    

----------------------------------------------------------------------
Ran 1435 tests in 19.310s

FAILED (failures=1)
<nose.result.TextTestResult run=1435 errors=0 failures=1>
>>> 
```

**Comment by mcflugen** [comment] 2017-05-31 17:25
@glaubius: Thanks for finding and reporting this.

The problem is that the `number_of_simulations` keyword defaults to 250.0 (that is, a float) but `np.ones` needs its `shape` argument to be integers. I'm not sure why our CI tests didn't pick this up.

@saisiddu this appears to be your component, could you please have a look and fix this? Thanks!

**Comment by Malley1** [comment] 2017-08-09 15:40
Hi,
I am having a similar error, running on Linux (Ubuntu 16.04), and conda 4.3.23. Any update?

**Comment by nicgaspar** [comment] 2017-08-09 18:52
@Malley1 Thanks for reporting this. It is annoying to see a test failure, and we should definitely fix this. In the meantime, this test failure does not stop you from running code that uses Landlab (beyond the tests!).

**Comment by Malley1** [comment] 2017-08-10 09:54
Ok, as long as it's just the test... Everything else does seem to be working fine for me so far, thanks!

**Comment by mcflugen** [comment] 2017-08-14 17:39
I see the problem. With versions of numpy < 1.13 the following issued a deprecation warning,
```python
np.empty(4.)
```
That is, passing a float argument to `empty`, `ones`, `zeros`, etc.  With numpy 1.13, this gives an error, not just a warning. Unfortunately, we're not regularly testing with numpy 1.13 yet but we really should be.

@Malley1, @glaubius: I assume you are using numpy 1.13, is that correct?

@saisiddu, will you please update your component to remove this error? I imagine it should be as easy as changing the default for `number_of_simulations` from `250.0` to `250`.

**Comment by saisiddu** [comment] 2017-08-14 18:29
@mcflugen: We did modify this and the master shows that default is 250 (int). Can you please let me know where is the error exactly?

**Comment by mcflugen** [comment] 2017-08-14 19:24
@saisiddu You'll have to work with @Malley1 and @glaubius to find out exactly where the error is but if you've fixed the default for `number_of_simulations` so that it's an `int`, I suspect this problem is fixed.

@Malley1, @glaubius It appears you are working off of forks that are a little out-of-date with the main landlab repository. If you update your forks, this error should be fixed.

**Comment by glaubius** [comment] 2017-08-17 18:14
@mcflugen @saisiddu I updated my fork of landlab and re-ran the tests. Everything works now!

Ran 1435 tests in 25.282s

OK
Out[2]: <nose.result.TextTestResult run=1435 errors=0 failures=0>

**Closed** 2017-08-17 18:56 UTC
Labels: bug
